services:
  golfAPI:
    image: joeyjowhi/golf_api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://database-1.cluster-cpi4sgc6w6oe.us-east-1.rds.amazonaws.com/golf_db
      - spring.datasource.username=admin
      - spring.datasource.password=adminpassword
